name: Run Task Every 1 Minutes

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - name: Call Base44 Function
        run: |
          curl -X POST https://projetobranco.base44.app/api/apps/69582b4b8596ea9ad6a1a4d2/functions/EnviarMensagemProgramada \
            -H "Content-Type: application/json"
